# Generated by Django 3.2.4 on 2021-07-01 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='send_excel',
        ),
    ]
